networks:
  foodgram_network:
    driver: bridge

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - foodgram_network
    container_name: foodgram_db

  backend:
    image: andrievskis1228/foodgram_backend
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - foodgram_network
    container_name: foodgram_backend
  frontend:
    image: andrievskis1228/foodgram_frontend
    volumes:
      - frontend_volume:/app/build/
    command: >
      sh -c "cp -r /app/build/static /app/build/*.js /app/build/*.css /app/build/*.html /app/build/*.ico /app/build/*.png /static_from_frontend/ && nginx -g 'daemon off;'"
    networks:
      - foodgram_network
    container_name: foodgram_frontend

  gateway:
    image: andrievskis1228/foodgram_gateway
    env_file: .env
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend_volume:/usr/share/nginx/html/  # Путь к фронтенду
      - static_volume:/app/static/
      - media_volume:/app/media/
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram_network
    container_name: foodgram_gateway

volumes:
  db_data:
  static_volume:
  media_volume:
  frontend_volume: