version: '3.8'
services:
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    networks:
      - foodgram-network

  front:
    build: ../frontend
    ports:
      - "3000:3000"
    networks:
      - foodgram-network

networks:
  foodgram-network:
    driver: bridge
