# Generated by Django 4.2 on 2025-08-24 11:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        help_text='Пользователь, на которого оформлена подписку',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscribers',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Автор',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='Пользователь, оформивший подписку',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscriptions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Подписчик',
                    ),
                ),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'avatar',
                    models.ImageField(
                        blank=True,
                        upload_to='users/avatars/',
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ['png', 'jpg', 'jpeg']
                            )
                        ],
                        verbose_name='Аватар',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(
                fields=['user'], name='users_subsc_user_id_3be018_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(
                fields=['author'], name='users_subsc_author__32a342_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(
                check=models.Q(('user', models.F('author')), _negated=True),
                name='no_self_subscribe',
            ),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(
                fields=('user', 'author'), name='unique_subscription'
            ),
        ),
    ]
