# Generated by Django 4.2 on 2025-08-27 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(
                blank=True,
                default='',
                null=True,
                upload_to='users/avatars/',
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ['png', 'jpg', 'jpeg']
                    )
                ],
                verbose_name='Аватар',
            ),
        ),
    ]
